spring.application.name=lab_results
spring.data.mongodb.uri=mongodb://localhost:27017/vet-clinic
server.port=8084

mqtt.broker=tcp://localhost:1883
mqtt.client-id=pet-analyzer-client
mqtt.inbound.topic=pet/vitals
mqtt.outbound.topic=pet/analyzed

thresholds.heart-rate-max=200
thresholds.heart-rate-min=30
thresholds.respiration-max=40
thresholds.respiration-min=10
thresholds.distance-from-home-max=10

gateway.url=http://localhost:8888

app.base-url=http://localhost:${server.port}

minio.endpoint=http://localhost:9000
minio.access-key=minioadmin
minio.secret-key=minioadmin
minio.bucket=pet-health-analyzer
minio.model-object=model.pkl