spring.application.name=lab_results
spring.data.mongodb.uri=mongodb://localhost:27017/vet-clinic
server.port=8084

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080/realms/clinic-realm
spring.security.oauth2.client.registration.appointment.client-id=appointment-service
spring.security.oauth2.client.registration.appointment.client-secret=KndP9iogTlX3TrdkzuPWgZYzztsp9o8D
spring.security.oauth2.client.registration.appointment.authorization-grant-type=client_credentials
spring.security.oauth2.client.registration.appointment.provider=keycloak
spring.security.oauth2.client.provider.keycloak.issuer-uri=http://localhost:8080/realms/clinic-realm

mqtt.broker=tcp://localhost:1883
mqtt.client-id=pet-analyzer-client
mqtt.inbound.topic=pet/vitals
mqtt.outbound.topic=pet/anomalies

thresholds.heart-rate-max=200
thresholds.heart-rate-min=30
thresholds.respiration-max=40
thresholds.respiration-min=10
thresholds.distance-from-home-max=10

gateway.url=http://localhost:8888
python.url=http://localhost:5000

#minio.endpoint=http://localhost:9000
#minio.access-key=minioadmin
#minio.secret-key=minioadmin
#minio.bucket=pet-health-analyzer
#minio.model-object=model.pkl